name: rakuraku
description: "rakuraku"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  melos: ^3.0.1

  # 코드 생성 도구
  freezed: ^2.4.7
  build_runner: ^2.4.8
  retrofit_generator: ^9.1.7

flutter:
  uses-material-design: true