name: sample
description: Sample app for testing chat SDK & UI
publish_to: none
version: 0.0.1
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  chat_sdk:
    path: ../../packages/chat_sdk
  chat_ui:
    path: ../../packages/chat_ui
  dart_jsonwebtoken: ^2.17.0
  dio: ^5.8.0+1
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/gallery.svg
    - assets/icons/send.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appstore.png"
  adaptive_icon_background: "assets/playstore.png"
  adaptive_icon_foreground: "assets/playstore.png"
