name: chat_ui
description: A Flutter chat UI package
publish_to: none
version: 0.0.1
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  chat_sdk:
    path: ../chat_sdk
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  flutter_image_compress: ^2.4.0
  fpdart: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/gallery.svg
    - assets/icons/send.svg
